# Generated by Django 2.0 on 2018-03-01 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_client', '0007_auto_20141120_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsresource',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wmsresource',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='description',
            field=models.TextField(blank=True, help_text='Description for the map. If left blank, the WMS abstract text will be used.'),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='east',
            field=models.FloatField(blank=True, help_text='Eastern boundary in decimal degrees. Will default to maxima of all layers.', null=True),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='layers',
            field=models.TextField(blank=True, help_text='The layers to be included in the map. Separate with commas, no spaces between the commas. If left blank the top of the layer list tree will be used by default.'),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='max_zoom',
            field=models.IntegerField(blank=True, default=19, help_text='Default minimum zoom level (0-19) for this map. Defaults to 19', null=True, validators=[django.core.validators.MaxValueValidator(19), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='min_zoom',
            field=models.IntegerField(blank=True, help_text='Default minimum zoom level (0-19) for this map.', null=True, validators=[django.core.validators.MaxValueValidator(19), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='name',
            field=models.CharField(help_text='A name for the WMS map.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='north',
            field=models.FloatField(blank=True, help_text='Northern boundary in decimal degrees. Will default to maxima of all layers.', null=True),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='preview',
            field=models.ImageField(blank=True, help_text='Preview image for this WMS Resource.', upload_to='wms_preview'),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='south',
            field=models.FloatField(blank=True, help_text='Southern boundary in decimal degrees. Will default to minima of all layers.', null=True),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='uri',
            field=models.CharField(help_text='URI for the WMS resource', max_length=100),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='west',
            field=models.FloatField(blank=True, help_text='Western boundary in decimal degrees. Will default to minima of all layers.', null=True),
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='zoom',
            field=models.IntegerField(blank=True, help_text='Default zoom level (1-19) for this map.', validators=[django.core.validators.MaxValueValidator(19), django.core.validators.MinValueValidator(0)]),
        ),
    ]
