# Generated by Django 2.0 on 2018-03-01 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_client', '0009_wmslayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsresource',
            name='zoom',
            field=models.IntegerField(blank=True, default=16, help_text='Default zoom level (1-19) for this map.', validators=[django.core.validators.MaxValueValidator(19), django.core.validators.MinValueValidator(0)]),
        ),
    ]
