# Generated by Django 2.0 on 2018-03-01 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms_client', '0010_auto_20180301_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('legend_uri', models.TextField(blank=True, null=True)),
                ('wmslayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_client.WMSLayer')),
            ],
        ),
        migrations.AlterField(
            model_name='wmsresource',
            name='zoom',
            field=models.IntegerField(blank=True, help_text='Default zoom level (1-19) for this map.', null=True, validators=[django.core.validators.MaxValueValidator(19), django.core.validators.MinValueValidator(0)]),
        ),
    ]
