# Generated by Django 2.2.1 on 2019-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_client', '0012_remove_wmsresource_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsresource',
            name='uri',
            field=models.TextField(help_text='URI for the WMS resource'),
        ),
    ]
